[auth]
redirect_uri="https://ncchatbot3.streamlit.app/oauth2callback"
cookie_secret="8f3e9d2a7b1c4f6e9a2d5c8b1f4a7e3d9c2b5f8a1d4e7a0c3f6b9e2d5a8c1f"

[auth.google]
client_id="81493866978-g61e8afh7vsnpf1voql701470tk9qhnp.apps.googleusercontent.com"
client_secret="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"
server_metadata_url="https://accounts.google.com/.well-known/openid-configuration"
client_kwargs = { scope = "openid email profile", prompt = "select_account" }